# Allow using clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary
font_family IosevkaTerm Nerd Font Mono
font_size 22

# Colors
background #181818
foreground #d8d8d8

window_margin_width 10
# Cursor
cursor_shape block

# Scrollback
scrollback_lines 10000

# # Zoom in / out like in apps
map ctrl+equal increase_font_size
map ctrl+minus decrease_font_size
